site_name: MyProject

theme:
  name: cinder

nav:
  - Home: index.md
  - Prerequisites: prerequisites.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md

site_url: https://chaitramara-dell.github.io/MyProject/

